version: "3.8"

services:
  python:
    container_name: python
    build:
      context: .
      dockerfile: dockerfiles/python/Dockerfile
    volumes:
      - ./:/app
    ports:
      - "5678:5678"
    tty: true
